### ISSUE TITLE
Invalid ISO Data: Uk and RK

### ISSUE THREAD

**Issue by bonbonio** [ilyankou/passport-index-dataset#6]
Hello,

This is an excellent data source; but I have found two errors;

The iso_2 UK is officially reserved, and should not be retained in this dataset, it is not an alias for the United Kingdom, as it uses GB for all iso-3166-2 datasets.

The iso_2 RK is also officially unused, and should not be assigned to Kosovo unless the ISO standard does (Which it doesnt)

**Comment by ilyankou** [comment]
@bonbonio 

Thanks for pointing these out! The reason is that Passport Index folks use UK code internally in their source JavaScript to represent the UK, and same for Kosovo (RK). I will change those to GB and XK accordingly.

As for your initial suggestion to represent the dataset in **tidy** format instead of as a distance matrix, I completely agree -- will do!

**Comment by ilyankou** [comment]
@bonbonio You should see the changes in the latest commit.
